server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/products-ecommerce-app
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect